baseURL = 'https://n-atsushi.github.io/myblog/'
languageCode = 'ja'
title = 'n-atsushi blog'
theme = "hugo-blog-awesome"
defaultContentLanguage = "ja"
enableEmoji = true
publishDir = "public"

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
	[markup.tableOfContents]
		startLevel = 2 # ToC starts from H2
		endLevel = 4 # ToC ends at H4
		ordered = false # generates <ul> instead of <ol>

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/n-atsushi"
 
[Languages.ja]
  languageName = "Japanese"
  languageCode = "ja"
  contentDir = "content/"
  weight = 1

[Languages.ja.menu]
  [[Languages.ja.menu.main]] 
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[Languages.ja.menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[Languages.ja.menu.main]]
    pageRef="about"
    name = 'About'
    url = '/about'
    weight = 30
  [[Languages.ja.menu.main]]
    pageRef="skill"
    name = 'Skill'
    url = '/skill'
    weight = 40
 [[Languages.ja.menu.main]]
    pageRef="Categories"
    name = 'Categories'
    url = '/categories/'
    weight = 50
[Languages.ja.params]
  sitename = "n-atsushi blog"
  defaultColor = "dark" 
  description = "n-atushi blog"
  mainSections = ['posts']
  toc = false 
  tocOpen = false 
  goToTop = true
  # additionalScripts = ['js/custom.js', 'js/custom-2.js']
  dateFormat = "2006-01-02" # date format used to show dates on various pages. If nothing is specified, then "2 Jan 2006" format is used.
  rssFeedDescription = "summary" # available options: 1) summary 2) full

[Languages.ja.params.author]
  avatar = "avator.png" # put the file in assets folder; also ensure that image has same height and width
  intro = "Atsushi blog"
  name = "n-atsushi"
  description = "I love sauna and Genius."

[Languages.ja.params.webmanifest]
  name = "blog"
  short_name = "blog"
  start_url = "/"
  theme_color = "#434648"
  background_color = "#fff"
  display = "standalone"